import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css"
import { AosInit } from "@/components/aos/aos.init";
import { ThemeProvider } from "@/components/theme/ThemeProvider";
import ClientLayout from "./client.layout";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 
  return (
    <html lang="en"
   suppressHydrationWarning
>
      <body className={`${poppins.className} antialiased`}>
        <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
        >
        <ClientLayout>
          {children}
          <AosInit />
        </ClientLayout>
        </ThemeProvider>
       
      </body>
    </html>
  );
}
